name: OpenWrt + Mihomo Build

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt.git
  REPO_BRANCH: openwrt-24.10
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison gawk \
        gcc-multilib git libncurses5-dev libssl-dev python3 unzip \
        zlib1g-dev file wget rsync time qemu-utils libelf-dev

    - name: Clone OpenWrt
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt

    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Add Mihomo + OpenClash
      run: |
        cd openwrt/package

        git clone https://github.com/vernesong/OpenClash
        git clone https://github.com/MetaCubeX/mihomo

    - name: Load config
      run: |
        cp .config openwrt/.config || true

    - name: Defconfig
      run: |
        cd openwrt
        make defconfig

    - name: Download packages
      run: |
        cd openwrt
        make download -j8

    - name: Build firmware
      run: |
        cd openwrt
        make -j$(nproc)

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-mihomo
        path: openwrt/bin
